[package]
name = "examples"
description = "Copied from ash, adapted to Vulkayes"
version = "0.1.0"
authors = ["TheEdward162 <TheEdward162@gmail.com>", "maik klein <maikklein@googlemail.com>"]
edition = "2018"

[dependencies]
image = "0.10.4"

vulkayes-core = { path = "../vulkayes-core", features = ["single_thread"] }
vulkayes-window = { path = "../vulkayes-window", features = ["winit"] }

log = "0.4"
edwardium_logger = "1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.4", features = ["windef", "winuser"] }

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.17.1"
cocoa = "0.20.0"
objc = "0.2.7"
